import { Footer, Navbar } from "@/components";
import "./globals.css";
import { Unna } from "next/font/google";

const roboto = Unna({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Urban Garden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
